# Generated by Django 3.2 on 2022-05-16 16:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsCard',
            fields=[
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit', models.DecimalField(decimal_places=6, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trx_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('transaction_date', models.DateTimeField()),
                ('paid_date', models.DateTimeField()),
                ('transaction_status', models.CharField(choices=[('closed', 'closed'), ('reversed', 'reversed'), ('pending', 'pending')], max_length=8)),
                ('approvement_status', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trx.benefitscard')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trx.company')),
            ],
        ),
        migrations.AddField(
            model_name='benefitscard',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trx.customer'),
        ),
    ]
